name: Maven Package

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  publish:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github
          cache: 'maven'

      - name: Fetch all dependencies
        run: mvn -B dependency:resolve-plugins verify
        env:
          GITHUB_TOKEN: ${{ secrets.MAVEN_READ_PKGS }}

      - name: Build and Publish to GitHub Packages
        run: mvn -B deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
